title: Hackintosh Compatibility Chart
author: Vini Moraes
description: >
  Information about hardware compatibility with every version of macOS

remote_theme: vinis-moraes/webtheme
minima:
  skin: dark
