title: Hackintosh Compatibility Chart
author: Vini Moraes
description: >
  Information about hardware compatibility with every version of macOS

plugins:
  - jekyll-remote-theme
remote_theme: vinis-moraes/webtheme
minima:
  skin: dark
